// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOxZZYI5Rze0m4SmC8nElcydZK7jZvAbA',
    appId: '1:702749896800:web:9e93b10f3f3fc143b5d305',
    messagingSenderId: '702749896800',
    projectId: 'auth-84957',
    authDomain: 'auth-84957.firebaseapp.com',
    storageBucket: 'auth-84957.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRb7e6tIhn4pnz--L8CqGNru_z1i-a3Kg',
    appId: '1:702749896800:android:bc42972db7fd3ed0b5d305',
    messagingSenderId: '702749896800',
    projectId: 'auth-84957',
    storageBucket: 'auth-84957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-k8LOVXQvE6ho9Ppsu6UAEuPg4OpZdI',
    appId: '1:702749896800:ios:f20eee174bd73787b5d305',
    messagingSenderId: '702749896800',
    projectId: 'auth-84957',
    storageBucket: 'auth-84957.appspot.com',
    androidClientId: '702749896800-2s1d6gl5u4qpkr481gcr6knv3s7ktkk0.apps.googleusercontent.com',
    iosClientId: '702749896800-ctd8iivgjnmvtinhdvfi5q0e15i5s1ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-k8LOVXQvE6ho9Ppsu6UAEuPg4OpZdI',
    appId: '1:702749896800:ios:47d62172e3f36e63b5d305',
    messagingSenderId: '702749896800',
    projectId: 'auth-84957',
    storageBucket: 'auth-84957.appspot.com',
    androidClientId: '702749896800-2s1d6gl5u4qpkr481gcr6knv3s7ktkk0.apps.googleusercontent.com',
    iosClientId: '702749896800-4imjdpumdci6po0mj3b3t85q5qal3io8.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicLogin.RunnerTests',
  );
}
